language: minimal
os: linux
dist: focal

branches:
  only:
    - master

arch: 
  - amd64
  - arm64

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t brunoshiroma/benchtool_julia:$TRAVIS_CPU_ARCH .
  - docker push brunoshiroma/benchtool_julia:$TRAVIS_CPU_ARCH
